### ISSUE TITLE
fix: plugin fails to load in OpenCode Desktop app (Bun SEA require() async ESM rejection)

### ISSUE THREAD

**Issue by clarkbalan** [prosperitypirate/codexfi#144]
## Bug

The codexfi plugin fails to load in the OpenCode Desktop app (macOS `.app` bundle) with:

```
require() async module ".../lancedb/dist/index.js" is unsupported.
use "await import()" instead. failed to load plugin
```

Followed by repeated:
```
Plugin export is not a function failed to load plugin
```

## Root Cause

PR #142 fixed the original `lancedb.connect is not a function` crash by replacing the static ESM import with `createRequire()`. This works in the terminal CLI's Bun SEA binary, but the Desktop app's Bun SEA binary rejects `require()` on async ESM modules.

Both binaries are OpenCode `1.3.15` but have different hashes — they were compiled separately and have different `require()` behavior for async ESM modules.

## Fix

Replace `createRequire` with `await import("@lancedb/lancedb")` in `plugin/src/db.ts`. Dynamic `import()` is the standard async module loading mechanism and works in all environments: Node.js, Bun, Bun SEA (terminal), Bun SEA (desktop).

## Environments

| Environment | Binary | `createRequire` | `await import()` |
|-------------|--------|-----------------|-------------------|
| Terminal CLI | Bun SEA (120M, hash `9076...`) | works | works |
| Desktop GUI | Bun SEA (120M, hash `a5c7...`) | **fails** | works |

## Reproduction

1. Open OpenCode Desktop app
2. Check `~/Library/Logs/ai.opencode.desktop/` for latest log
3. See `require() async module ... is unsupported` error

## Related

- #141 — original lancedb.connect crash
- #142 — createRequire fix (partial — terminal only)
